//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4005
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class nisan : object, System.ComponentModel.INotifyPropertyChanged {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order", typeof(nisanOrder))]
    [System.Xml.Serialization.XmlElementAttribute("purchase", typeof(nisanPurchase))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
            this.RaisePropertyChanged("Items");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class nisanOrder : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string nameField;
    
    private string jawiField;
    
    private string bornField;
    
    private string bornmField;
    
    private string deathField;
    
    private string deathmField;
    
    private string ageField;
    
    private string itemField;
    
    private string remarksField;
    
    private string tagsField;
    
    private string soldtoField;
    
    private string dateField;
    
    private string deliveredField;
    
    private string billField;
    
    private decimal priceField;
    
    private bool priceFieldSpecified;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("name");
        }
    }
    
    /// <remarks/>
    public string jawi {
        get {
            return this.jawiField;
        }
        set {
            this.jawiField = value;
            this.RaisePropertyChanged("jawi");
        }
    }
    
    /// <remarks/>
    public string born {
        get {
            return this.bornField;
        }
        set {
            this.bornField = value;
            this.RaisePropertyChanged("born");
        }
    }
    
    /// <remarks/>
    public string bornm {
        get {
            return this.bornmField;
        }
        set {
            this.bornmField = value;
            this.RaisePropertyChanged("bornm");
        }
    }
    
    /// <remarks/>
    public string death {
        get {
            return this.deathField;
        }
        set {
            this.deathField = value;
            this.RaisePropertyChanged("death");
        }
    }
    
    /// <remarks/>
    public string deathm {
        get {
            return this.deathmField;
        }
        set {
            this.deathmField = value;
            this.RaisePropertyChanged("deathm");
        }
    }
    
    /// <remarks/>
    public string age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
            this.RaisePropertyChanged("age");
        }
    }
    
    /// <remarks/>
    public string item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
            this.RaisePropertyChanged("item");
        }
    }
    
    /// <remarks/>
    public string remarks {
        get {
            return this.remarksField;
        }
        set {
            this.remarksField = value;
            this.RaisePropertyChanged("remarks");
        }
    }
    
    /// <remarks/>
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
            this.RaisePropertyChanged("tags");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string soldto {
        get {
            return this.soldtoField;
        }
        set {
            this.soldtoField = value;
            this.RaisePropertyChanged("soldto");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
            this.RaisePropertyChanged("date");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string delivered {
        get {
            return this.deliveredField;
        }
        set {
            this.deliveredField = value;
            this.RaisePropertyChanged("delivered");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bill {
        get {
            return this.billField;
        }
        set {
            this.billField = value;
            this.RaisePropertyChanged("bill");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
            this.RaisePropertyChanged("price");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
            this.RaisePropertyChanged("priceSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class nisanPurchase : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string buyfromField;
    
    private string dateField;
    
    private string quantityField;
    
    private decimal priceField;
    
    private bool priceFieldSpecified;
    
    private string itemField;
    
    private string remarksField;
    
    /// <remarks/>
    public string buyfrom {
        get {
            return this.buyfromField;
        }
        set {
            this.buyfromField = value;
            this.RaisePropertyChanged("buyfrom");
        }
    }
    
    /// <remarks/>
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
            this.RaisePropertyChanged("date");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
            this.RaisePropertyChanged("quantity");
        }
    }
    
    /// <remarks/>
    public decimal price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
            this.RaisePropertyChanged("price");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified {
        get {
            return this.priceFieldSpecified;
        }
        set {
            this.priceFieldSpecified = value;
            this.RaisePropertyChanged("priceSpecified");
        }
    }
    
    /// <remarks/>
    public string item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
            this.RaisePropertyChanged("item");
        }
    }
    
    /// <remarks/>
    public string remarks {
        get {
            return this.remarksField;
        }
        set {
            this.remarksField = value;
            this.RaisePropertyChanged("remarks");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
